// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcu_1zBGYWMn9_Wrrrkjp4P_2RDDavyeM',
    appId: '1:363962091639:web:ad5517cfc35155461e1e72',
    messagingSenderId: '363962091639',
    projectId: 'login-696f2',
    authDomain: 'login-696f2.firebaseapp.com',
    storageBucket: 'login-696f2.appspot.com',
    measurementId: 'G-MN2BTSJPY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUK9pld4xbDDJu_NKneDJZHbpvHR8CxVI',
    appId: '1:363962091639:android:c3e60ce37efbf9691e1e72',
    messagingSenderId: '363962091639',
    projectId: 'login-696f2',
    storageBucket: 'login-696f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnruuUVy1DAKB9S3-WIJdir0e59aDzCvk',
    appId: '1:363962091639:ios:c9dcd358a02dced31e1e72',
    messagingSenderId: '363962091639',
    projectId: 'login-696f2',
    storageBucket: 'login-696f2.appspot.com',
    iosBundleId: 'com.example.firebaseSignin',
  );
}
